import { z } from "zod";
import { PetSchema } from "../types/pet.type";

/**
 * Create Pet DTO
 * Used when creating a new pet.
 * Excludes fields generated by the database.
 */
export const CreatePetDTO = PetSchema.omit({
  _id: true,
  createdAt: true,
  updatedAt: true,
});

export type CreatePetDTO = z.infer<typeof CreatePetDTO>;

/**
 * Update Pet DTO
 * Every field is optional because users may update
 * only part of a pet.
 */
export const UpdatePetDTO = CreatePetDTO.partial();

export type UpdatePetDTO = z.infer<typeof UpdatePetDTO>;